"""Add recipe metadata

Revision ID: 9a230cb1a22e
Revises: ae141b6109fc
Create Date: 2026-07-16 13:26:00.570053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a230cb1a22e'
down_revision = 'ae141b6109fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cook_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('cook_time')
        batch_op.drop_column('servings')

    # ### end Alembic commands ###
