"""Initial migration

Revision ID: ae141b6109fc
Revises: 
Create Date: 2026-07-13 11:25:04.043077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae141b6109fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
